{
 "title": "New Trade Dashboard",
 "description": "Monitoring for trading team",
 "tags": [ "Trading" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "PnL Reporting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Net Asset Value",
   "type": "stat",
   "description": "The net asset value of the account, including open positions.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nav_gauge != 0" }
   ]
  },
  {
   "title": "Total Exposure",
   "type": "stat",
   "description": "The total notional value of all open positions.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_exposure_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Absolute PnL ",
   "type": "stat",
   "description": "The current PnL (realised + unrealised).",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "abs_pnl_gauge" }
   ]
  },
  {
   "title": "Relative PnL",
   "type": "stat",
   "description": "Relative PnL (from manually set reference)",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rel_pnl_gauge*100" }
   ]
  },
  { "title": "Risk Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Leverage",
   "type": "gauge",
   "description": "The account leverage (calculated from total exposure divided by NAV).",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "leverage_gauge" }
   ]
  },
  {
   "title": "Current Drawdown (%)",
   "type": "gauge",
   "description": "The current drawdown from the maximum NAV.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drawdown_gauge*100" }
   ]
  },
  {
   "title": "Open Positions",
   "type": "stat",
   "description": "The number of open positions.",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pos_gauge" }
   ]
  },
  {
   "title": "Maximum Position Percentage (%NAV)",
   "type": "stat",
   "description": "The percentage of NAV which the maximum position holds.",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max_pos_frac_gauge*100 != 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Maximum Position Value ($)",
   "type": "stat",
   "description": "The notional value of the largest position.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max_position_gauge != 0\n" }
   ]
  },
  { "title": "Histories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Net Asset Value History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "nav_gauge != 0" }
   ]
  },
  {
   "title": "Total Exposure History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "total_exposure_gauge != 0" }
   ]
  },
  {
   "title": "Net Exposure History (Long - Short)",
   "type": "timeseries",
   "description": "The signed sum of long and short exposure. A positive value indicates a long bias, whereas a negative value indicates a short bias.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "targets": [
    { "expr": "net_exposure_gauge != 0" }
   ]
  },
  {
   "title": "Position count history",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "targets": [
    { "expr": "pos_gauge != 0" }
   ]
  }
 ]
}